In [2]:
import numpy as np

In [17]:
a = np.array([1, 2, 3], dtype = 'int16')
print(a)

[1 2 3]


In [6]:
b = np.array([[7.0, 6.0, 2.0], [2.0, 4.0, 6.9]])
print(b)

[[7.  6.  2. ]
 [2.  4.  6.9]]


In [8]:
print(a * b)

[[ 7.  12.   6. ]
 [ 2.   8.  20.7]]


In [11]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
a.shape

(3,)

In [14]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int16')

In [16]:
b.dtype

dtype('float64')

In [19]:
a.itemsize

2

In [20]:
b.itemsize

8

In [22]:
a.nbytes

6

# Accessing

In [24]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [27]:
print(a[:, 5])

[ 6 13]


In [26]:
a[1][5]

13

# initalizing

In [32]:
print(np.zeros([4,8]))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [33]:
np.ones([4,3,2])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [34]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [35]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [36]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
np.random.rand(4,2,3)

array([[[0.02677301, 0.78382419, 0.1219519 ],
        [0.30028024, 0.94631602, 0.38929517]],

       [[0.48404506, 0.12484833, 0.35971712],
        [0.74666424, 0.90128955, 0.49760246]],

       [[0.64395452, 0.39164017, 0.60308503],
        [0.8854978 , 0.48267871, 0.2445166 ]],

       [[0.40683051, 0.12001883, 0.85796138],
        [0.41380212, 0.25636557, 0.75515521]]])

In [42]:
np.random.random(a.shape)

array([[0.34336736, 0.48948146, 0.00473575, 0.54089241, 0.82565286,
        0.59318318, 0.82049311],
       [0.57155718, 0.37560363, 0.95725068, 0.01732934, 0.30788509,
        0.17772775, 0.60100504]])

In [43]:
np.random.randint(7, size = (3,3))

array([[3, 0, 2],
       [6, 3, 4],
       [2, 6, 1]])

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [5]:
print(np.ones((5,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
z = np.ones((5,5))
z[2, 2] = 0
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
#copying the data

a = np.array([1, 2, 3])
b = a
print(b)

[1 2 3]


In [9]:
b[0] = 100
print(b)

[100   2   3]


In [10]:
print(a)

[100   2   3]


In [11]:
a = np.array([1, 2, 3])
b = a.copy()
print(b)

[1 2 3]


In [12]:
b[0] = 100
print(b)

[100   2   3]


In [13]:
print(a)

[1 2 3]


In [32]:
#mathematics

a = np.array([5, 6, 7, 8])


In [27]:
a - 2

array([3, 4, 5, 6])

In [28]:
a * 2

array([10, 12, 14, 16])

In [29]:
a / 2

array([2.5, 3. , 3.5, 4. ])

In [30]:
a +=2
a

array([ 7,  8,  9, 10])

In [33]:
a + 2

array([ 7,  8,  9, 10])

In [34]:
a ** 2

array([25, 36, 49, 64], dtype=int32)

# linear Algebra

In [35]:
a = np.ones((2, 3))
print(a)

b = np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [39]:
m = np.matmul(a, b)
print(m)

[[6. 6.]
 [6. 6.]]


In [40]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [42]:
stats = np.array([[1, 2, 3],[4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [54]:
np.min(stats, axis = 1)

array([1, 4])

In [48]:
np.max(stats, axis = 1)

array([3, 6])

In [49]:
np.min(stats)

1

In [50]:
np.sum(stats)

21

In [51]:
np.sum(stats, axis = 0)

array([5, 7, 9])

In [52]:
before = np.array([[1, 2, 3, 4, 5, 6, 7, 8]])
print(before)

after = np.reshape(before,(8,1))
print(after)

[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [62]:
after = np.reshape(before,(4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [66]:
#vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

print(np.vstack([v1, v2]))

[[1 2 3 4]
 [5 6 7 8]]


In [68]:
print(np.vstack([v1, v2, v1, v2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


# Miscellaneous

### Load Data from file

In [76]:
np.genfromtxt('gopi.txt', delimiter = ',')

array([[ 13.,  42.,  43.,  44., 124., 132., 324.],
       [ 44.,  55.,  66.,  22., 554., 522., 235.],
       [ 45.,  45.,  23.,  35., 223., 344., 322.]])

In [84]:
filedata = np.genfromtxt('gopi.txt', delimiter = ',')
fd = filedata.astype('int32')
print(fd)

[[ 13  42  43  44 124 132 324]
 [ 44  55  66  22 554 522 235]
 [ 45  45  23  35 223 344 322]]


## Boolean Masking and advanced Indexing

In [89]:
fd[fd < 50]

array([13, 42, 43, 44, 44, 22, 45, 45, 23, 35])

In [91]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a[[1, 2, 7]]

array([2, 3, 8])

In [95]:
np.all(fd < 50, axis = 1)

array([False, False, False])

In [132]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [133]:
a[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [144]:
a[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [142]:
a[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [148]:
np.diagonal(a,1)

array([ 2,  8, 14, 20])

In [149]:
x1 = np.random.randint(10,size=6)  #one dimensional
x2 = np.random.randint(10,size=(3,4)) #two dimensional
x3 = np.random.randint(10,size=(3,4,5)) #three dimensional

In [150]:
x1

array([8, 5, 4, 6, 6, 8])

In [151]:
x2

array([[3, 6, 0, 3],
       [7, 7, 3, 4],
       [7, 3, 8, 3]])

In [152]:
x3

array([[[5, 2, 5, 0, 6],
        [0, 6, 6, 9, 1],
        [1, 2, 4, 0, 7],
        [1, 1, 2, 1, 3]],

       [[8, 2, 8, 7, 3],
        [6, 3, 0, 1, 4],
        [5, 1, 9, 2, 2],
        [4, 2, 7, 1, 9]],

       [[6, 1, 0, 2, 2],
        [5, 2, 3, 6, 2],
        [7, 6, 3, 1, 0],
        [3, 5, 6, 9, 2]]])

In [153]:
print("x3 ndim",x3.ndim)
print("x3 shape",x3.shape)
print("x3 size",x3.size)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


In [154]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [155]:
x = [1,2,3,33,33,6,7]
x1,x2,x3 =np.split(x,[3,5])

In [156]:
x1,x2,x3

(array([1, 2, 3]), array([33, 33]), array([6, 7]))

In [157]:
x = np.array([1,2,3])

In [158]:
np.mean(x)

2.0

In [159]:
np.median(x)

2.0